CREATE SCHEMA RBAICDB AUTHORIZATION SA;

CREATE TABLE RBAICDB.CUSTOMERS (
	CNUM BIGINT PRIMARY KEY NOT NULL,
	BRANCHID INTEGER,
	COMPANYNUMBER INTEGER,
	CATEGORY INTEGER,
	NAME VARCHAR(64),
	PATRONYMIC VARCHAR(64),
	SURNAME VARCHAR(64),
	KNF0 VARCHAR(128),
	DATEOFBIRTH DATE,
	PLACEOFBIRTH VARCHAR(128),
	LEGALADDRESS VARCHAR(512),	
	CURRENTADDRESS VARCHAR(512),	
	EMAIL VARCHAR(64),
	CURRENTADDRESSPHONE VARCHAR(32),
	CURRENTADDRESSFAX VARCHAR(32),
	PASSPORTSERIES VARCHAR(16),
	PASSPORTNUMBER VARCHAR(16),
	ISSUEDBY VARCHAR(64),
	ISSUEDDATE DATE,
	RESIDENTTYPE VARCHAR(1),
	EMAILSTATEMENTS INTEGER,
	COMPLIANCE INTEGER,
	PEP INTEGER,
	LASTMODIFIED TIMESTAMP
);

CREATE TABLE RBAICDB.CUSTOMERS_EMP (
	CNUM BIGINT PRIMARY KEY NOT NULL,
	BUNDLECODE VARCHAR(16),
	INN VARCHAR(32),
	CURRENTADDRESS_ID BIGINT,
	LEGALADDRESS_ID BIGINT
);

CREATE TABLE RBAICDB.KL_ADDRESS (
	ADDRESS_ID BIGINT PRIMARY KEY NOT NULL,
	KL_TOSTRING VARCHAR(512)
);
