CREATE SCHEMA RMCP AUTHORIZATION SA;
CREATE SCHEMA TERMINATOR AUTHORIZATION SA;

CREATE TABLE TERMINATOR.TERMINATOR_TOKEN (
	NAME VARCHAR(100) PRIMARY KEY NOT NULL,
	TIMESTAMP_VALUE TIMESTAMP
);

CREATE TABLE RMCP.CLIENT (
	ID BIGINT PRIMARY KEY NOT NULL,
	BRANCH_ID INTEGER,
	EMPLOYER_ID INTEGER,
	CATEGORY_ID SMALLINT,
	BUNDLE_TYPE_ID VARCHAR(8),
	FIRST_NAME VARCHAR(64),	
	LAST_NAME VARCHAR(64),
	PATRONYMIC VARCHAR(64),
	TRANSLIT_NAME VARCHAR(128),
	BIRTH_DATE DATE,
	BIRTH_PLACE VARCHAR(128),
	LEGAL_ADDRESS VARCHAR(1024),		
	EMAIL VARCHAR(64),
	INN VARCHAR(32),
	MOBILE_PHONE VARCHAR(32),
	PASSPORT_NUMBER VARCHAR(16),
	PASSPORT_ISSUER VARCHAR(64),
	PASSPORT_DATE DATE,
	RESIDENT SMALLINT,
	COMPLIANCE SMALLINT,
	PEP_TYPE_ID SMALLINT,
	LASTMODIFIED TIMESTAMP
);

INSERT INTO TERMINATOR.TERMINATOR_TOKEN(NAME, TIMESTAMP_VALUE) VALUES ('CLIENT', {ts '2013-03-31 00:00:00'});

INSERT INTO RMCP.CLIENT(ID) VALUES (2);